apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-deployment
  namespace: 2048-game
  labels:
    app: 2048-game
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: 2048-game
  strategy:
    type: RollingUpdate
    maxUnavailable: 1
    maxSurge: 1
  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: 2048-container
          image: docker.io/nithinkumar99/2048:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:  
               path: /
               port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5